[package]
name = "ascii_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.6"
thread_clock = "0.2.0"
termios = "0.3.3"
oneshot = "0.1.5"
